### ISSUE TITLE
General Updates Query

### ISSUE THREAD

**Issue by joreilly86** [rpakishore/ak_sap#6]
Hi Arun,

Just checking in on progress with ak_sap. I know you're likely busy but have you progressed things much since we spoke last? 👍

**Comment by rpakishore** [comment]
Hey James,

- I've added more methods to manipulate SAP2000.
- The code has been refactored to run more smoothly and intuitively.
- Set up some of the documentation to make it easier for new users to get started.
- I also plan to allocate some time to writing tests.

The module is already in a very usable state and I’ve been using it almost daily at work. I'm now looking for directions on what methods or functionality to implement next since it already meets many of my current project needs.

P.S. Seeing how useful this module is, I've started a new repository to achieve the same functionality for [CSI SAFE](https://github.com/rpakishore/ak_safe)

**Comment by joreilly86** [comment]
Amazing! You're crushing it! I am writing a tutorial for Pynite at the moment but would like to cover ak_sap next, with your approval. I can reach out to discuss once I have the time. Perhaps I can show a simple example of a 3D frame structure analysis and how ak_sap's methods work.

**Comment by rpakishore** [comment]
Absolutely feel free to. Let me know if you need anything. More than happy to help :D
